import { eventBus, BookingEventPayload } from "@/lib/events/bus";
import { prisma } from "@/lib/prisma";
import { assignHousekeepingTaskRoundRobin } from "@/lib/operations/round-robin";

export function initHousekeepingListeners() {
  eventBus.on<BookingEventPayload>('GUEST_CHECKED_OUT', async (payload) => {
    try {
      console.log(`[Housekeeping Listener] Guest checked out of Reservation ${payload.reservationId}. Initiating Housekeeping flow...`);

      // 1. First, fetch the exact Unit ID associated with this reservation
      const reservation = await prisma.reservation.findUnique({
        where: { id: payload.reservationId },
        select: { unitId: true, propertyId: true }
      });

      if (!reservation) {
        throw new Error(`Reservation ${payload.reservationId} not found.`);
      }

      // 2. Update the Unit status to DIRTY
      await prisma.unit.update({
        where: { id: reservation.unitId },
        data: { status: 'DIRTY' }
      });
      console.log(`[Housekeeping Listener] Unit ${reservation.unitId} updated to DIRTY.`);

      // 3. Prevent duplicate task creation if multiple events fire
      const existingTask = await prisma.housekeepingTask.findFirst({
        where: {
          unitId: reservation.unitId,
          type: 'CHECKOUT_CLEAN',
          status: { in: ['PENDING', 'ACCEPTED', 'IN_PROGRESS'] }
        }
      });

      if (existingTask) {
        console.log(`[Housekeeping Listener] Task already exists for Unit ${reservation.unitId}. Skipping duplicate creation.`);
        return;
      }

      // 4. Create the structured Housekeeping Task
      const task = await prisma.housekeepingTask.create({
        data: {
          unitId: reservation.unitId,
          propertyId: reservation.propertyId,
          type: 'CHECKOUT_CLEAN',
          status: 'PENDING',
          scheduledFor: new Date(), // Immediate
          notes: 'Automated checkout cleaning generated by Event Engine.'
        }
      });
      console.log(`[Housekeeping Listener] CHECKOUT_CLEAN Task created successfully for Unit ${reservation.unitId}.`);

      // 5. Automatically assign via round-robin and notify team
      await assignHousekeepingTaskRoundRobin(task.id);
      console.log(`[Housekeeping Listener] Task ${task.id} pushed to round-robin assignment.`);

    } catch (error) {
      console.error("[Housekeeping Listener Error - GUEST_CHECKED_OUT]", error);
    }
  });

  eventBus.on<{taskId: string, propertyId: string, unitId: string}>('HOUSEKEEPING_TASK_COMPLETED', async (payload) => {
    try {
      console.log(`[Housekeeping Listener] Task ${payload.taskId} completed. Processing automated inventory deductions...`);
      
      // 1. Fetch all inventory items for this property that have a defaultDeduction > 0
      const itemsToDeduct = await prisma.inventoryItem.findMany({
        where: {
          propertyId: payload.propertyId,
          defaultDeduction: { gt: 0 }
        }
      });

      if (itemsToDeduct.length === 0) {
        console.log(`[Housekeeping Listener] No inventory items with defaultDeduction > 0 found for property ${payload.propertyId}. Skipping.`);
        return;
      }

      // 2. Perform the deductions and check for low stock
      let deductionCount = 0;
      for (const item of itemsToDeduct) {
        // Prevent negative quantities
        const newQuantity = Math.max(0, item.quantity - item.defaultDeduction);
        
        await prisma.inventoryItem.update({
          where: { id: item.id },
          data: { quantity: newQuantity }
        });
        deductionCount++;
        
        if (newQuantity < item.minThreshold && item.quantity >= item.minThreshold) {
          console.log(`[Inventory Alert] ${item.name} dropped below minThreshold (${newQuantity} < ${item.minThreshold}).`);
          // Could also emit a LOW_INVENTORY event here if needed later
        }
      }

      console.log(`[Housekeeping Listener] Successfully deducted ${deductionCount} inventory items for Task ${payload.taskId}.`);
    } catch (error) {
      console.error("[Housekeeping Listener Error - HOUSEKEEPING_TASK_COMPLETED]", error);
    }
  });

  console.log("[Housekeeping Listeners] Successfully initialized.");
}
