import { eventBus, BookingEventPayload } from "@/lib/events/bus";
import { prisma } from "@/lib/prisma";

export function initHousekeepingListeners() {
  eventBus.on<BookingEventPayload>('GUEST_CHECKED_OUT', async (payload) => {
    try {
      console.log(`[Housekeeping Listener] Guest checked out of Reservation ${payload.reservationId}. Initiating Housekeeping flow...`);

      // 1. First, fetch the exact Unit ID associated with this reservation
      const reservation = await prisma.reservation.findUnique({
        where: { id: payload.reservationId },
        select: { unitId: true, propertyId: true }
      });

      if (!reservation) {
        throw new Error(`Reservation ${payload.reservationId} not found.`);
      }

      // 2. Update the Unit status to DIRTY
      await prisma.unit.update({
        where: { id: reservation.unitId },
        data: { status: 'DIRTY' }
      });
      console.log(`[Housekeeping Listener] Unit ${reservation.unitId} updated to DIRTY.`);

      // 3. Prevent duplicate task creation if multiple events fire
      const existingTask = await prisma.housekeepingTask.findFirst({
        where: {
          unitId: reservation.unitId,
          type: 'CHECKOUT_CLEAN',
          status: { in: ['PENDING', 'ACCEPTED', 'IN_PROGRESS'] }
        }
      });

      if (existingTask) {
        console.log(`[Housekeeping Listener] Task already exists for Unit ${reservation.unitId}. Skipping duplicate creation.`);
        return;
      }

      // 4. Create the structured Housekeeping Task
      await prisma.housekeepingTask.create({
        data: {
          unitId: reservation.unitId,
          propertyId: reservation.propertyId,
          type: 'CHECKOUT_CLEAN',
          status: 'PENDING',
          scheduledFor: new Date(), // Immediate
          notes: 'Automated checkout cleaning generated by Event Engine.'
        }
      });
      console.log(`[Housekeeping Listener] CHECKOUT_CLEAN Task created successfully for Unit ${reservation.unitId}.`);

    } catch (error) {
      console.error("[Housekeeping Listener Error - GUEST_CHECKED_OUT]", error);
    }
  });

  console.log("[Housekeeping Listeners] Successfully initialized.");
}
