import { prisma } from "@/lib/prisma"
import { OperationsClient } from "@/components/operations/operations-client"

export const revalidate = 15

export default async function OperationsPage() {
  const [tickets, housekeepingTasks, properties, units, teamMembers] = await Promise.all([
    prisma.ticket.findMany({
      include: {
        property: true,
        unit: true,
        guest: true,
        assignedTo: true,
        auditLogs: { orderBy: { createdAt: 'desc' } }
      },
      orderBy: { createdAt: 'desc' }
    }),
    prisma.housekeepingTask.findMany({
      include: { property: true, unit: true, assignedTo: true },
      orderBy: { createdAt: 'desc' }
    }),
    prisma.property.findMany({
      orderBy: { name: 'asc' },
      select: { id: true, name: true }
    }),
    prisma.unit.findMany({
      orderBy: { name: 'asc' },
      select: { id: true, name: true, propertyId: true }
    }),
    prisma.teamMember.findMany({
      where: { isActive: true },
      orderBy: { name: 'asc' },
      select: { id: true, name: true, role: true, propertyId: true, department: true }
    })
  ])

  const formattedTasks = housekeepingTasks.map(task => {
    let mappedStatus = 'OPEN'
    if (task.status === 'ACCEPTED') mappedStatus = 'ASSIGNED'
    if (task.status === 'IN_PROGRESS') mappedStatus = 'IN_PROGRESS'
    if (task.status === 'COMPLETED') mappedStatus = 'RESOLVED'

    return {
      id: task.id,
      title: `[Auto Task] ${task.type.replace('_', ' ')}`,
      description: `Automated housekeeping task generated by system.`,
      category: 'HOUSEKEEPING',
      priority: 'HIGH',
      status: mappedStatus,
      property: task.property,
      propertyId: task.propertyId,
      unit: task.unit,
      unitId: task.unitId,
      guest: null,
      assignedTo: task.assignedTo,
      assignedToId: task.assignedToId,
      createdAt: task.createdAt,
      updatedAt: task.updatedAt,
      isAutoTask: true
    }
  })

  const combinedData = [...tickets, ...formattedTasks].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())

  // Calculate stats
  const total = combinedData.length
  const open = combinedData.filter(t => t.status === 'OPEN' || t.status === 'TRIAGED').length
  const inProgress = combinedData.filter(t => t.status === 'ASSIGNED' || t.status === 'ACKNOWLEDGED' || t.status === 'IN_PROGRESS').length
  const resolved = combinedData.filter(t => t.status === 'RESOLVED' || t.status === 'VERIFIED' || t.status === 'CLOSED').length

  const stats = {
    total,
    open,
    inProgress,
    resolved
  }

  return <OperationsClient initialData={combinedData} stats={stats} properties={properties} units={units} teamMembers={teamMembers} />
}
