import { prisma } from "@/lib/prisma"
import { OperationsClient } from "@/components/operations/operations-client"

export const dynamic = 'force-dynamic'

export default async function OperationsPage() {
  const tickets = await prisma.ticket.findMany({
    include: {
      property: true,
      unit: true,
      guest: true,
      assignedTo: true,
      auditLogs: {
        orderBy: { createdAt: 'desc' }
      }
    },
    orderBy: {
      createdAt: 'desc'
    }
  })

  const housekeepingTasks = await prisma.housekeepingTask.findMany({
    include: {
      property: true,
      unit: true,
      assignedTo: true,
    },
    orderBy: {
      createdAt: 'desc'
    }
  })

  const formattedTasks = housekeepingTasks.map(task => {
    let mappedStatus = 'OPEN'
    if (task.status === 'ACCEPTED') mappedStatus = 'ASSIGNED'
    if (task.status === 'IN_PROGRESS') mappedStatus = 'IN_PROGRESS'
    if (task.status === 'COMPLETED') mappedStatus = 'RESOLVED'

    return {
      id: task.id,
      title: `[Auto Task] ${task.type.replace('_', ' ')}`,
      description: `Automated housekeeping task generated by system.`,
      category: 'HOUSEKEEPING',
      priority: 'HIGH',
      status: mappedStatus,
      property: task.property,
      unit: task.unit,
      guest: null,
      assignedTo: task.assignedTo,
      createdAt: task.createdAt,
      updatedAt: task.updatedAt,
      isAutoTask: true
    }
  })

  const combinedData = [...tickets, ...formattedTasks].sort((a, b) => b.createdAt.getTime() - a.createdAt.getTime())

  // Fetch all units so they can be selected when creating a ticket
  const units = await prisma.unit.findMany({
    orderBy: { name: 'asc' },
    select: { id: true, name: true }
  })

  // Fetch team members for assignment (need propertyId and department for round-robin/filtering)
  const teamMembers = await prisma.teamMember.findMany({
    where: { isActive: true },
    orderBy: { name: 'asc' },
    select: { id: true, name: true, role: true, propertyId: true, department: true }
  })

  // Calculate stats
  const total = combinedData.length
  const open = combinedData.filter(t => t.status === 'OPEN' || t.status === 'TRIAGED').length
  const inProgress = combinedData.filter(t => t.status === 'ASSIGNED' || t.status === 'ACKNOWLEDGED' || t.status === 'IN_PROGRESS').length
  const resolved = combinedData.filter(t => t.status === 'RESOLVED' || t.status === 'VERIFIED' || t.status === 'CLOSED').length

  const stats = {
    total,
    open,
    inProgress,
    resolved
  }

  return <OperationsClient initialData={combinedData} stats={stats} units={units} teamMembers={teamMembers} />
}
